name: Cargo global dependency
description: Install a global cargo dependency with `cargo install`
inputs:
  name:
    required: true
    description: Package name
  binary-name:
    description: Binary name if different from package name
  version:
    description: Version to install. Defaults to latest
  release:
    description: Install release version instead of debug
    default: 'false'
  force-version:
    description: Force the given version if a different version is installed
    default: 'false'
  flags:
    description: Additional flags to pass on to the install command, one per line
    required: false
runs:
  using: node20
  main: index.js
